export const questions = [
	{
		question: 'How can I use Minecraftblocked?',
		answer: (
			<>
				To use Minecraftblocked, you can either browse through all the blocked servers, or find a specific one by typing
				its hostname or server address in the search box on our homepage. Our system will then automatically match the
				server with our database of identified server hashes.
			</>
		),
	},
	{
		question: 'What is a server hash and why is it used?',
		answer: (
			<>
				A server hash is a string of characters that is generated by applying a hash function to the IP address or
				hostname of a server. Mojang, the company behind Minecraft, uses server hashes instead of revealing the actual
				IP addresses for security and privacy reasons. Hashes are used to uniquely identify the servers without exposing
				sensitive details.
			</>
		),
	},
	{
		question: 'How do I get the hash of a server?',
		answer: (
			<>
				If you are a server owner, you can type in your server hostname (e.g. play.hypixel.net) or your ip address into
				our searchbox on the homepage and our search will give you further details about the block such as the hash &
				date.
			</>
		),
	},
	{
		question: 'How often is the list of blocked servers updated?',
		answer: (
			<>
				Our system crawls the Mojang blocked servers API every 60 minutes and updates our database as soon as we detect
				any changes. This ensures that our information is as up-to-date as possible.
			</>
		),
	},
	{
		question: 'What should I do if my server is listed as blocked?',
		answer: (
			<>
				If your server is listed as blocked, you should contact Mojang support for assistance. There may be a variety of
				reasons why a server is blocked, and they can provide you with more specific information and possible solutions.
			</>
		),
	},
	{
		question: 'Can I contribute to the database of known public Minecraft servers?',
		answer: (
			<>
				Yes, we appreciate community contributions. If you own or know of a public Minecraft server that is not in our
				database, you can submit its information through the contact section of our website. Please ensure that the
				information provided is accurate and up to date.
			</>
		),
	},
];
